# Generated by Django 5.1.15 on 2026-05-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=512)),
                ('intermediate_file', models.FileField(upload_to='html/intermediate/')),
                ('result_file', models.FileField(upload_to='html/result/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
